[package]
name = "loam"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
arc-swap = "1.7.1"
match_opt = "0.1.2"
elsa = { version = "1.9.0", git = "https://github.com/lurk-lab/elsa", branch = "sync_frozen", features = ["indexmap"] }
indexmap = { version = "2.2.6", features = ["rayon"] }
rayon = "1.10.0"
p3-air = { git = "https://github.com/lurk-lab/Plonky3.git", branch = "sp1-new" }
p3-baby-bear = { git = "https://github.com/lurk-lab/Plonky3.git", branch = "sp1-new" }
p3-field = { git = "https://github.com/lurk-lab/Plonky3.git", branch = "sp1-new" }
p3-matrix = { git = "https://github.com/lurk-lab/Plonky3.git", branch = "sp1-new" }

[workspace]
members = ["examples/calculator"]

[profile.dev-ci]
inherits = "dev"
# By compiling dependencies with optimizations, performing tests gets much faster.
opt-level = 3
overflow-checks = true
lto = "thin"
incremental = false
codegen-units = 16
