[package]
name = "loam"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[workspace.dependencies]
rayon = "1.10.0"
itertools = "0.13.0"
p3-air = { git = "https://github.com/plonky3/Plonky3.git", branch = "main" }
p3-baby-bear = { git = "https://github.com/plonky3/Plonky3.git", branch = "main" }
p3-field = { git = "https://github.com/plonky3/Plonky3.git", branch = "main" }
p3-matrix = { git = "https://github.com/plonky3/Plonky3.git", branch = "main" }
p3-commit = { git = "https://github.com/plonky3/Plonky3.git", branch = "main" }
p3-challenger = { git = "https://github.com/plonky3/Plonky3.git", branch = "main" }
p3-maybe-rayon = { git = "https://github.com/plonky3/Plonky3.git", branch = "main" }
p3-uni-stark = { git = "https://github.com/plonky3/Plonky3.git", branch = "main" }
p3-util = { git = "https://github.com/plonky3/Plonky3.git", branch = "main" }
wp1-core = { git = "ssh://git@github.com/wormhole-foundation/wp1.git", branch = "dev" }

[dependencies]
arc-swap = "1.7.1"
match_opt = "0.1.2"
elsa = { version = "1.9.0", git = "https://github.com/lurk-lab/elsa", branch = "sync_frozen", features = ["indexmap"] }
indexmap = { version = "2.2.6", features = ["rayon"] }
rayon = { workspace = true }
itertools = { workspace = true }
p3-air = { workspace = true }
p3-baby-bear = { workspace = true }
p3-field = { workspace = true }
p3-matrix = { workspace = true }
p3-commit = { workspace = true }
p3-challenger = { workspace = true }
p3-maybe-rayon = { workspace = true }
p3-util = { workspace = true }


[workspace]
members = ["examples/calculator", "examples/byte_lookup"]

[profile.dev-ci]
inherits = "dev"
# By compiling dependencies with optimizations, performing tests gets much faster.
opt-level = 3
overflow-checks = true
lto = "thin"
incremental = false
codegen-units = 16
