[package]
name = "loam-macros"
version = "0.1.0"
description = "Custom derives for `loam`"
edition.workspace = true

[lib]
proc-macro = true

[dependencies]
proc-macro2 = "1.0.66"
quote = "1.0.31"
syn = { version = "1.0.109", features = ["full"] }
