# Opens a PR to update the nightly Rust version every two weeks
name: Rust Version Check

on:
  workflow_dispatch:
  schedule:
    - cron:  '0 0 1,15 * *'

jobs:
  rust-version-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@nightly
      - uses: actions/checkout@v4
        with:
          repository: argumentcomputer/ci-workflows
          path: ci-workflows
      - uses: ./ci-workflows/.github/actions/rust-version
        id: rust-version
        with:
          toolchain: nightly
      - uses: tibdex/github-app-token@v2
        if: steps.rust-version.outputs.outdated == 'true'
        id: generate-token
        with:
          app_id: ${{ secrets.TOKEN_APP_ID }}
          private_key: ${{ secrets.TOKEN_APP_PRIVATE_KEY }}
      # Open PR if Rust version is out of date with latest nightly
      - name: Create Pull Request
        if: steps.rust-version.outputs.outdated == 'true'
        uses: peter-evans/create-pull-request@v7
        with:
          token: ${{ steps.generate-token.outputs.token }}
          branch: "ci-update-rust-version"
          title: "chore: Update Rust version to `nightly-${{ steps.rust-version.outputs.new-version }}`"
          commit-message: "chore: Update Rust version to `nightly-${{ steps.rust-version.outputs.new-version }}`"
          labels: "automated-issue"
          reviewers: "arthurpaulino, wwared, huitseeker, samuelburnham"
          body: |
            This is an automated PR updating the Rust version from `nightly-${{ steps.rust-version.outputs.old-version }}` to `nightly-${{ steps.rust-version.outputs.new-version }}`

            Workflow run: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
